<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tailcat</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>Tailcat</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Cbor" Version="10.0.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.7.0" />
  </ItemGroup>

</Project>
