<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tailcat.WebDemo</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>Tailcat.WebDemo</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
