<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Tailcat.Demo</RootNamespace>
    <AssemblyName>tailcat-demo</AssemblyName>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tailcat.Link\Tailcat.Link.csproj" />
    <ProjectReference Include="..\Tailcat.Net\Tailcat.Net.csproj" />
  </ItemGroup>

</Project>
