<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Tailcat.Derp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sodium.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tailcat\Tailcat.csproj" />
  </ItemGroup>

</Project>
